=== PPatrik123/ZW7DOR_XMLGyak/XMLTaskZW7DOR/XMLSchemaZW7DOR.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
     
       <xs:element name="kiszallito_rendszer">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="etterem" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Nyitvatartas" type="xs:string"></xs:element>
                                                 <xs:element name="Nev" type="xs:string"></xs:element>
                                                 <xs:element name="Elerhetoseg">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="Telefonszam" type="xs:int"></xs:element>
                                                                      <xs:element name="Weboldal" type="xs:string"></xs:element>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="ET_ID" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="futar" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Nev" type="xs:string"></xs:element>
                                                 <xs:element name="Telefonszam" type="xs:int"></xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="F_ID" type="xs:int"></xs:attribute>
                                          <xs:attribute name="ET_IDREF" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="beszallito" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Nev" type="xs:string"></xs:element>
                                                 <xs:element name="Elerhetoseg" type="xs:string"></xs:element>
                                                 <xs:element name="Cim">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="Varos" type="xs:string"></xs:element>
                                                                      <xs:element name="Iranyitoszam" type="xs:int"></xs:element>
                                                                      <xs:element name="Utca" type="xs:string"></xs:element>
                                                                      <xs:element name="Hazszam" type="xs:int"></xs:element>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="Be_ID" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="beszallitas" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Hozzavalo" type="xs:string"></xs:element>
                                                 <xs:element name="Datum" type="xs:date"></xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="Be_IDREF" type="xs:int"></xs:attribute>
                                          <xs:attribute name="ET_IDREF" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="etel" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="etel_neve" type="xs:string"></xs:element>
                                                 <xs:element name="teljes_ar" type="xs:int"></xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="Etel_ID" type="xs:int"></xs:attribute>
                                          <xs:attribute name="ET_IDREF" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="vevo" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Nev" type="xs:string"></xs:element>
                                                 <xs:element name="Telefonszam" type="xs:int"></xs:element>
                                                 <xs:element name="Cim">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="Utca" type="xs:string"></xs:element>
                                                                      <xs:element name="Varos" type="xs:string"></xs:element>
                                                                      <xs:element name="Hazszam" type="xs:int"></xs:element>
                                                                      <xs:element name="Iranyitoszam" type="xs:int"></xs:element>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="vevo_ID" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="bankartya" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Bank" type="xs:string"></xs:element>
                                                 <xs:element name="Lejarati_datum" type="xs:date"></xs:element>
                                                 <xs:element name="Tipus" type="xs:string"></xs:element>
                                             </xs:sequence>
                                          <xs:attribute name="kartyaszam" type="xs:int"></xs:attribute>
                                          <xs:attribute name="vevo_IDREF" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                     <xs:attribute name="xmlns:xs" type="xs:string"></xs:attribute>
                     <xs:attribute name="xs:noNamespaceSchemaLocation" type="xs:string"></xs:attribute>
                 </xs:complexType>
          </xs:element>
   </xs:schema>

=== PPatrik123/ZW7DOR_XMLGyak/XMLTaskZW7DOR/DOMParseZW7DOR/teszt.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<kiszallito_rendszer xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaZW7DOR.xsd">
        
    <!--Étterem-->
        
    <etterem ET_ID="4">
                
        <Nyitvatartas>11től 22:30ig</Nyitvatartas>
        		
        <Nev>Kalipszo</Nev>
                
        <Elerhetoseg>
                        
            <Telefonszam>209876543</Telefonszam>
            		    
            <Weboldal>kalipszo.hu</Weboldal>
                    
        </Elerhetoseg>
            
    </etterem>
        
    <etterem ET_ID="2">
                
        <Nyitvatartas>9től 21ig</Nyitvatartas>
        		
        <Nev>Vendelin</Nev>
                
        <Elerhetoseg>
                        
            <Telefonszam>208765432</Telefonszam>
            		    
            <Weboldal>vendelin.hu</Weboldal>
                    
        </Elerhetoseg>
            
    </etterem>
        
    <etterem ET_ID="3">
                
        <Nyitvatartas>8tól 22ig</Nyitvatartas>
        		
        <Nev>Molnár Csárda</Nev>
                
        <Elerhetoseg>
                        
            <Telefonszam>306876546</Telefonszam>
            		    
            <Weboldal>molnarcsarda.hu</Weboldal>
                    
        </Elerhetoseg>
            
    </etterem>
        
    <!--Futár-->
        
    <futarok>
                
        <futar ET_IDREF="1" F_ID="1">
                        
            <Nev>Lajos Balázs</Nev>
                        
            <Telefonszam>202354342</Telefonszam>
                    
        </futar>
                
        <futar ET_IDREF="2" F_ID="2">
                        
            <Nev>Horváth Lajos</Nev>
                        
            <Telefonszam>203521958</Telefonszam>
                    
        </futar>
                
        <futar ET_IDREF="3" F_ID="3">
                        
            <Nev>Palkó Patrik</Nev>
                        
            <Telefonszam>202572553</Telefonszam>
                    
        </futar>
            
        <futar F_ID="4">
            <Nev>Katona János</Nev>
            <Telefonszam>200000</Telefonszam>
        </futar>
    </futarok>
        
    <!--Beszállító-->
        
    <beszallito Be_ID="4">
                
        <Nev>Kis Piac</Nev>
                
        <Elerhetoseg>kis.piac@gmail.com</Elerhetoseg>
                
        <Cim>
                        
            <Varos>Kazincbarcika</Varos>
                        
            <Iranyitoszam>3700</Iranyitoszam>
                        
            <Utca>Fő utca</Utca>
                        
            <Hazszam>35</Hazszam>
                    
        </Cim>
            
    </beszallito>
        
    <beszallito Be_ID="2">
                
        <Nev>Nagy piac</Nev>
                
        <Elerhetoseg>nagy.piac@gmail.com</Elerhetoseg>
                
        <Cim>
                        
            <Varos>Encs</Varos>
                        
            <Iranyitoszam>3896</Iranyitoszam>
                        
            <Utca>Fő utca</Utca>
                        
            <Hazszam>25</Hazszam>
                    
        </Cim>
            
    </beszallito>
        
    <beszallito Be_ID="3">
                
        <Nev>Közepes piac</Nev>
                
        <Elerhetoseg>közepes.piac@gmail.com</Elerhetoseg>
                
        <Cim>
                        
            <Varos>Miskolc</Varos>
                        
            <Iranyitoszam>3885</Iranyitoszam>
                        
            <Utca>Fő utca</Utca>
                        
            <Hazszam>15</Hazszam>
                    
        </Cim>
            
    </beszallito>
        
    <!--Beszállítás-->
        
    <beszallitas Be_IDREF="1" ET_IDREF="1">
                
        <Hozzavalo>banán</Hozzavalo>
                
        <Datum>2022.08.06</Datum>
            
    </beszallitas>
        
    <beszallitas Be_IDREF="2" ET_IDREF="2">
                
        <Hozzavalo>csoki</Hozzavalo>
                
        <Datum>2022.03.01</Datum>
            
    </beszallitas>
        
    <beszallitas Be_IDREF="3" ET_IDREF="3">
                
        <Hozzavalo>alma</Hozzavalo>
                
        <Datum>2022.10.21</Datum>
            
    </beszallitas>
        
    <!--Étel-->
        
    <etelek>
                
        <etel ET_IDREF="1" Etel_ID="1">
                        
            <etel_neve>Banános palacsinta</etel_neve>
                        
            <teljes_ar>2500</teljes_ar>
                    
        </etel>
                
        <etel ET_IDREF="2" Etel_ID="2">
                        
            <etel_neve>Csokis zserbó</etel_neve>
                        
            <teljes_ar>3400</teljes_ar>
                    
        </etel>
                
        <etel ET_IDREF="3" Etel_ID="3">
                        
            <etel_neve>Disznó almával a szájában</etel_neve>
                        
            <teljes_ar>25000</teljes_ar>
                    
        </etel>
            
        <etel Etel_ID="4">
            <etel_neve>Mákos Guba</etel_neve>
            <teljes_ar>7000</teljes_ar>
            <ET_IDREF>4</ET_IDREF>
        </etel>
    </etelek>
        
    <!--Vevő-->
        
    <vevo vevo_ID="1">
                
        <Nev>Palkó Zsolti</Nev>
                
        <Telefonszam>202566311</Telefonszam>
                
        <Cim>
                        
            <Utca>Károlyi Gáspár</Utca>
                        
            <Varos>Szerencs</Varos>
                        
            <Hazszam>5</Hazszam>
                        
            <Iranyitoszam>3880</Iranyitoszam>
                    
        </Cim>
            
    </vevo>
        
    <vevo vevo_ID="2">
                
        <Nev>Lakatos Valentin</Nev>
                
        <Telefonszam>202599210</Telefonszam>
                
        <Cim>
                        
            <Utca>Kálmán</Utca>
                        
            <Varos>Budapest</Varos>
                        
            <Hazszam>31</Hazszam>
                        
            <Iranyitoszam>3550</Iranyitoszam>
                    
        </Cim>
            
    </vevo>
        
    <vevo vevo_ID="3">
                
        <Nev>Raul Patricio</Nev>
                
        <Telefonszam>202599901</Telefonszam>
                
        <Cim>
                        
            <Utca>Nagy Lajos</Utca>
                        
            <Varos>Pálháza</Varos>
                        
            <Hazszam>2</Hazszam>
                        
            <Iranyitoszam>3770</Iranyitoszam>
                    
        </Cim>
            
    </vevo>
        
    
    <!--Bankártya-->
        
    <bankartya kartyaszam="7629746286234247" vevo_IDREF="1">
                
        <Bank>OTP</Bank>
                
        <Lejarati_datum>2025.10.28</Lejarati_datum>
                
        <Tipus>betéti kártya</Tipus>
            
    </bankartya>
        
    <bankartya kartyaszam="(0543345349664954" vevo_IDREF="1">
                
        <Bank>MKB</Bank>
                
        <Lejarati_datum>2025.10.29</Lejarati_datum>
                
        <Tipus>hitelkártya</Tipus>
            
    </bankartya>
        
    <bankartya kartyaszam="5432467233423432" vevo_IDREF="1">
                
        <Bank>CIB Bank</Bank>
                
        <Lejarati_datum>2025.10.30</Lejarati_datum>
                
        <Tipus>többfunkciós kártya</Tipus>
            
    </bankartya>
    
</kiszallito_rendszer>
